#
#ident	"@(#)Makefile	1.o	92/10/30 SMI"
#
# Copyright (c) 1992 by Sun Microsystems, Inc.
#

FSTYPE=		pcfs
LIBPROG=	fstyp
ATTMK=		$(LIBPROG)

include		../../Makefile.fstype

LDLIBS += -lintl

lint:		lint_PROG
