/*
 * Copyright (c) 1994, by Sun Microsystems, Inc.
 *
 * This code is MKS code ported to Solaris with minimum modifications so that
 * upgrades from MKS will readily integrate. Avoid modification if possible!
 */
#ident	"@(#)m_locale.h 1.1	94/10/12 SMI"

/*
 * m_locale.h: mks extentions to locale.h
 * The client may have chosen to define their own extentions similar
 * to these in their locale.h -- thus if M_I18N_MKS_FULL is set
 * we will not define these structures, on the assumption that they
 * are defined in locale.h
 *
 * Copyright 1992 by Mortice Kern Systems Inc.  All rights reserved.
 *
 * This Software is unpublished, valuable, confidential property of
 * Mortice Kern Systems Inc.  Use is authorized only in accordance
 * with the terms and conditions of the source licence agreement
 * protecting this Software.  Any unauthorized use or disclosure of
 * this Software is strictly prohibited and will result in the
 * termination of the licence agreement.
 *
 * If you have any questions, please consult your supervisor.
 * 
 * $Header: /u/rd/h/RCS/m_locale.h,v 1.5 1992/07/03 10:38:31 alex Exp $
 */
#ifndef	__M_M_LOCALE_H__
#define	__M_M_LOCALE_H__

#ifndef	M_I18N_MKS_FULL

/*
 * Date/time format.
 * MKS extension: structure pointer returned by localedtconv()
 */
struct m_dtconv {
        char    *date_time_format;      /* date and time format */
        char    *date_format;           /* date format */
        char    *time_format;           /* time format */
        char    *time_format_ampm;      /* long date format */
        char    *am_string;             /* AM string */
        char    *pm_string;             /* PM string */
        char    *abbrev_day_names[7];   /* abbreviated weekday names */
        char    *day_names[7];          /* full weekday names */
        char    *abbrev_month_names[12];/* abbreviated month names */
        char    *month_names[12];       /* full month names */
};

/*l
 * Declare the _m_localedef structure.
 * Contains codeset information of corrent locale.
 * This structure is used only by locale command.
 * It is generated by the localedef utility and is put in the LC_LOCDEF file.
 * MKS extention: structure pointer returned by localeldconv()
 * In this case, where we have no interaction with the mks ansi-c libraries,
 * we #define localeldconv to _m_locdef which is in the file ldconv.c,
 * which, if compiled in this mode will not generate the actual function.
 */
struct _m_localedef {
        char    *charmap;
        char    *code_set_name;
        char    escape_char;
        char    comment_char;
        int     mb_cur_max;
        int     mb_cur_min;
};

/*
 * Note: If I18N is turned off, then these functions will get redefined
 * into direct address of structures in the m_i18n.h file
 */
LEXTERN struct m_dtconv		*m_localedtconv ANSI((void));
LEXTERN struct _m_localedef	*m_localeldconv ANSI((void));

LEXTERN	struct m_dtconv		_m_dtconv;
LEXTERN	struct _m_localedef	_m_locdef;
LEXTERN	struct lconv		_m_lconv;

#endif	/* !M_I18N_MKS_FULL */
#endif
