#
#ident	"@(#)Makefile	1.3	95/02/14 SMI"
#
# Copyright (c) 1994, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/sparc/sun4u/Makefile
#
# Platform-specific, but shared between platforms.
#

PLATFORM =	sun4u
ARCHVERS =	v9
TOPDIR =	../../../../../..

include ../Makefile.com
