/*	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)t_getstate.c	1.14	94/03/02 SMI"
		/* SVr4.0 1.4.2.1	*/

#include "timt.h"
#include <errno.h>
#include <sys/types.h>
#include <rpc/trace.h>
#include <sys/stream.h>
#include <sys/stropts.h>
#include <sys/tihdr.h>
#include <sys/timod.h>
#include <tiuser.h>
#include <stdio.h>
#include <sys/signal.h>
#include "tli.h"

t_getstate(fd)
int fd;
{
	register struct _ti_user *tiptr;

	trace2(TR_t_getstate, 0, fd);
	if ((tiptr = _t_checkfd(fd)) == NULL) {
		int sv_errno = errno;
		trace2(TR_t_getstate, 1, fd);
		errno = sv_errno;
		return (-1);
	}

	switch (tiptr->ti_state) {

	case T_UNBND:
	case T_IDLE:
	case T_INCON:
	case T_OUTCON:
	case T_DATAXFER:
	case T_INREL:
	case T_OUTREL:
		trace2(TR_t_getstate, 1, fd);
		return (tiptr->ti_state);
	case T_FAKE:
	case T_HACK:
	/*
	 * (Following ancient comment no longer true but
	 * T_HACK is exposed in tiuser.h now - sigh !!
	 * ===========================================
	 * T_HACK needed to maintain compatibility!!!
	 * DO NOT REMOVE UNTIL _spec FILE REORDERED!!!!
	 *
	 * It's purpose is to keep the size of the data
	 * generated by the compilation of the switch
	 * statement the same as before (range of 12).  If it is removed
	 * or changed the locations of the imported symbols
	 * will change, breaking compatibility.
	 * ============================================
	 */
	default:
		t_errno = TSTATECHNG;
		trace2(TR_t_getstate, 1, fd);
		return (-1);
	}
}
