#
# uts/sun4e/Makefile.rules
# Copyright (c) 1991 by Sun Microsystems, Inc.
#
#ident   "@(#)Makefile.rules 1.22     94/03/23 SMI"
#
#	This Makefile defines the build rules for the directory uts/sun4e
#	and it's children. These are the source files which sun4e
#	"implementation architecture" dependent.
#

#
#	This was implemented by pattern matching rules of the form:
#
# $(OBJS_DIR)/%.o:	 $(UTSBASE)/common/os/%.c
#	$(COMPILE.c) -o $@ $<
#
# $(LINTS_DIR)/%.ln:	$(UTSBASE)/common/os/%.c
#	@($(LHEAD) $(LINT.c) $< $(LTAIL))
#
#	For each directory containing source. This proved to slow under
#	Nse because it caused a significant additional number of stats
#	and stats are real slow under TFS. If TFS performance should
#	improve, one might consider returning to the former implementation.
#	In the former implementation, this file (Makefile.rules) was not
#	needed and the pattern matching rules were in Makefile.files.
#

#
#	C object build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#
$(OBJS_DIR)/swtch.o:            $(UTSBASE)/sun4e/ml/swtch.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4e/ml/swtch.s

$(OBJS_DIR)/confunix.o:		$(UTSBASE)/sun4e/conf/confunix.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/conf/confunix.c

$(OBJS_DIR)/autoconf.o:		$(UTSBASE)/sun4e/io/autoconf.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/io/autoconf.c

$(OBJS_DIR)/hardclk.o:		$(UTSBASE)/sun4e/io/hardclk.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/io/hardclk.c

$(OBJS_DIR)/copy.o:		$(UTSBASE)/sun4e/ml/copy.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4e/ml/copy.s

$(OBJS_DIR)/ip_ocsum.o:		$(UTSBASE)/sun4e/ml/ip_ocsum.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4e/ml/ip_ocsum.s

$(OBJS_DIR)/locore.o:		$(UTSBASE)/sun4e/ml/locore.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4e/ml/locore.s

$(OBJS_DIR)/map.o:		$(UTSBASE)/sun4e/ml/map.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4e/ml/map.s

$(OBJS_DIR)/memerr.o:		$(UTSBASE)/sun4e/ml/memerr.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/ml/memerr.c

$(OBJS_DIR)/eccerr.o:		$(UTSBASE)/sun4e/ml/eccerr.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/ml/eccerr.c

$(OBJS_DIR)/subr_4e.o:		$(UTSBASE)/sun4e/ml/subr_4e.s
	$(COMPILE.s) -o $@ $(UTSBASE)/sun4e/ml/subr_4e.s

$(OBJS_DIR)/bp_map.o:		$(UTSBASE)/sun4e/os/bp_map.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/bp_map.c

$(OBJS_DIR)/ddi_impl.o:		$(UTSBASE)/sun4e/os/ddi_impl.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/ddi_impl.c

$(OBJS_DIR)/dvma.o:		$(UTSBASE)/sun4e/os/dvma.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/dvma.c

$(OBJS_DIR)/kalloc.o:		$(UTSBASE)/sun4e/os/kalloc.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/kalloc.c

$(OBJS_DIR)/machdep.o:		$(UTSBASE)/sun4e/os/machdep.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/machdep.c

$(OBJS_DIR)/mlsetup.o:		$(UTSBASE)/sun4e/os/mlsetup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/mlsetup.c

$(OBJS_DIR)/ppage.o:		$(UTSBASE)/sun4e/os/ppage.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/ppage.c

$(OBJS_DIR)/rootnex.o:		$(UTSBASE)/sun4e/os/rootnex.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/rootnex.c

$(OBJS_DIR)/startup.o:		$(UTSBASE)/sun4e/os/startup.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/startup.c

$(OBJS_DIR)/stubs.o:		$(UTSBASE)/sun4e/os/stubs.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/stubs.c

$(OBJS_DIR)/trap.o:		$(UTSBASE)/sun4e/os/trap.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/os/trap.c

$(OBJS_DIR)/hat_conf.o:		$(UTSBASE)/sun4e/vm/hat_conf.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/vm/hat_conf.c

$(OBJS_DIR)/mmu.o:		$(UTSBASE)/sun4e/vm/mmu.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/vm/mmu.c

$(OBJS_DIR)/vm_machdep.o:	$(UTSBASE)/sun4e/vm/vm_machdep.c
	$(COMPILE.c) -o $@ $(UTSBASE)/sun4e/vm/vm_machdep.c

#
#	Lint `object' build rules
#
#	The following are alphabetized by source file path. Please maintain
# this ordering.
#
$(LINTS_DIR)/swtch.ln:          $(UTSBASE)/sun4e/ml/swtch.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4e/ml/swtch.s $(LTAIL))

$(LINTS_DIR)/confunix.ln:	$(UTSBASE)/sun4e/conf/confunix.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/conf/confunix.c $(LTAIL))

$(LINTS_DIR)/autoconf.ln:	$(UTSBASE)/sun4e/io/autoconf.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/io/autoconf.c $(LTAIL))

$(LINTS_DIR)/hardclk.ln:	$(UTSBASE)/sun4e/io/hardclk.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/io/hardclk.c $(LTAIL))

$(LINTS_DIR)/copy.ln:		$(UTSBASE)/sun4e/ml/copy.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4e/ml/copy.s $(LTAIL))

$(LINTS_DIR)/ip_ocsum.ln:	$(UTSBASE)/sun4e/ml/ip_ocsum.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4e/ml/ip_ocsum.s $(LTAIL))

$(LINTS_DIR)/locore.ln:		$(UTSBASE)/sun4e/ml/locore.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4e/ml/locore.s $(LTAIL))

$(LINTS_DIR)/map.ln:		$(UTSBASE)/sun4e/ml/map.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4e/ml/map.s $(LTAIL))

$(LINTS_DIR)/memerr.ln:		$(UTSBASE)/sun4e/ml/memerr.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/ml/memerr.c $(LTAIL))

$(LINTS_DIR)/eccerr.ln:		$(UTSBASE)/sun4e/ml/eccerr.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/ml/eccerr.c $(LTAIL))

$(LINTS_DIR)/subr_4e.ln:	$(UTSBASE)/sun4e/ml/subr_4e.s
	@($(LHEAD) $(LINT.s) $(UTSBASE)/sun4e/ml/subr_4e.s $(LTAIL))

$(LINTS_DIR)/bp_map.ln:		$(UTSBASE)/sun4e/os/bp_map.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/bp_map.c $(LTAIL))

$(LINTS_DIR)/ddi_impl.ln:	$(UTSBASE)/sun4e/os/ddi_impl.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/ddi_impl.c $(LTAIL))

$(LINTS_DIR)/dvma.ln:		$(UTSBASE)/sun4e/os/dvma.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/dvma.c $(LTAIL))

$(LINTS_DIR)/kalloc.ln:		$(UTSBASE)/sun4e/os/kalloc.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/kalloc.c $(LTAIL))

$(LINTS_DIR)/machdep.ln:	$(UTSBASE)/sun4e/os/machdep.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/machdep.c $(LTAIL))

$(LINTS_DIR)/mlsetup.ln:	$(UTSBASE)/sun4e/os/mlsetup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/mlsetup.c $(LTAIL))

$(LINTS_DIR)/ppage.ln:		$(UTSBASE)/sun4e/os/ppage.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/ppage.c $(LTAIL))

$(LINTS_DIR)/rootnex.ln:	$(UTSBASE)/sun4e/os/rootnex.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/rootnex.c $(LTAIL))

$(LINTS_DIR)/startup.ln:	$(UTSBASE)/sun4e/os/startup.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/startup.c $(LTAIL))

$(LINTS_DIR)/stubs.ln:		$(UTSBASE)/sun4e/os/stubs.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/stubs.c $(LTAIL))

$(LINTS_DIR)/trap.ln:		$(UTSBASE)/sun4e/os/trap.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/os/trap.c $(LTAIL))

$(LINTS_DIR)/hat_conf.ln:	$(UTSBASE)/sun4e/vm/hat_conf.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/vm/hat_conf.c $(LTAIL))

$(LINTS_DIR)/mmu.ln:		$(UTSBASE)/sun4e/vm/mmu.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/vm/mmu.c $(LTAIL))

$(LINTS_DIR)/vm_machdep.ln:	$(UTSBASE)/sun4e/vm/vm_machdep.c
	@($(LHEAD) $(LINT.c) $(UTSBASE)/sun4e/vm/vm_machdep.c $(LTAIL))
