#
#ident	"@(#)Makefile	1.20	94/03/28 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)

install:	all $(ROOTDYNLIB)

lint:		$(LINTLIB)

include		../Makefile.targ
