#
#ident "@(#)Makefile	1.5	94/11/22 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#
# psm/stand/cpr/sun4m/Makefile

include ../../../../Makefile.master

ARCH=		sun4m
MMU=		srmmu
MACH=		sparc
ARCHDIR=	../sun4m
MACHDIR=	../sparc
ARCHOBJ=	fixmmu_sun4m.o module.o module_asm.o cpr_sun4m.o sadiv.o
TARGET_ARCH=	-$(KARCH)
ARCHOPTS=
ARCHVER=	v7

include ../common/Makefile.com
