#
# ident "@(#)Makefile	1.2 94/11/08 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
