#
#ident	"@(#)Makefile	1.3	92/07/14 SMI"        /* SVr4.0
#

PROG= biff

include ../Makefile.ucbcmd

FILEMODE=	755

LDLIBS += -lintl

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.ucbtarg
