#
#ident	"@(#)Makefile	1.16	94/03/28 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

include		../Makefile.com

.KEEP_STATE:

all:		$(PROG)

install:	all $(ROOTCCSBINPROG)

native:		$(SGSPROTO)/$(PROG)

lint:		$(LINTOUT)

include		../Makefile.targ
