#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.10	95/03/01 SMI"

PROG= arch

include ../Makefile.cmd

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:

include ../Makefile.targ
