#
#ident	"@(#)Makefile	1.8	94/05/10 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

include		../Makefile.com

.KEEP_STATE:

all:		$(PROGS)  $(LIBS)

install:	all $(ROOTPROGS) $(ROOTLIBS)

include		../Makefile.targ
