#
#ident	"@(#)Makefile	1.2	92/07/14 SMI"        /* SVr4.0
#

PROG= touch

include ../Makefile.ucbcmd

FILEMODE=	755

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.ucbtarg
