#
#ident	"@(#)Makefile.targ	1.2	94/08/30 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

all:		$(PROG)

clean:
		$(RM) $(CLEANFILES)

delete:
		$(RM) $(PROG)

install:	all $(ROOTPROG)

lint:		$(LINTOUT)

$(PROG):	$(SRCS)  $(MAPFILE)
		$(LINK.c) -o $@ $(SRCS) $(LDLIBS)
		$(POST_PROCESS)

$(LINTOUT):	$(SRCS)
		$(LINT.c) $(SRCS) > $(LINTOUT) 2>&1

include		../../../Makefile.targ
