#
# Copyright (c) 1991 by Sun Microsystems, Inc.
#

#ident	"@(#)Makefile	1.9	93/06/06 SMI"

# The common Makefile does most of the work; this Makefile is here
# to give the NSE a private place to record dependencies.

PLATFORM =	sun4d
KARCHOBJS =	anlyzerr.o

include ../Makefile.com

