#
#ident	"@(#)Makefile	1.1	91/10/29 SMI"
#
# Copyright (c) 1991 by Sun Microsystems, Inc.
#

PROG= kbd

include ../Makefile.cmd

.KEEP_STATE:

all: $(PROG)

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
