#
#	Copyright (c) 1991 by Sun Microsystems, Inc.
#
#ident	"@(#)Makefile	1.15	94/02/28 SMI"
#

include		../Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)

install:	all $(ROOTDYNLIB)

lint:		$(LINTLIB)

include		../Makefile.targ
