#
#ident	"@(#)Makefile	1.2	94/12/10 SMI"
#
# Copyright (c) 1994, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/sparc/sun4m/Makefile
#
# Platform-specific, but shared between platforms.
# Bogusly SPARC Version 7 dependent.
#

PLATFORM =	sun4m
ARCHVERS =	v7
TOPDIR =	../../../../../..

include ../Makefile.com
