#!/bin/sh
#
# Copyright (c) 1994, by Sun Microsystems, Inc.
#
#ident	"@(#)initpcmcia	1.2	95/01/26 SMI"

#
# Pre network startup initialization for PCMCIA
#

case "$1" in
'start')
	if [ -c /dev/pcmcia ]
	then
# force the nexus in and then wait a while for stabilization
		for i in 1 2 3 4 5 6 7 8 9 10
		do
			sh -c 'echo </dev/pcmcia' >/dev/null 2>&1
		done
		
	fi
	;;
'stop')
	;;
*)
	echo "Usage: /etc/init.d/pcmcia { start | stop }"
	;;
esac
exit 0
