#
#ident	"@(#)Makefile	1.2	95/03/22 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES += i.preserve i.sbproconf

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
