#
#ident	"@(#)Makefile.targ	1.2	94/07/06 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

lint:		$(LINTLIB)

pics/%.o:	../common/%.c
		$(COMPILE.c) -o $@ $<
		$(POST_PROCESS_O)

%.o:		../common/%.c
		$(COMPILE.c) -o $@ $<
		$(POST_PROCESS_O)

delete:
		-$(RM) $(DYNLIB)

$(DYNLIB):	$(MAPFILE)

include		../../../../lib/Makefile.targ
