#
#ident	"@(#)Makefile	1.2	92/07/14 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

PROG= mkfile

include ../Makefile.cmd

LDLIBS += -lintl

.KEEP_STATE:

all: $(PROG)

install: all $(ROOTUSRSBINPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
